travis:
  secure:
    BINSTAR_TOKEN: vVhyLg01xxi3Z0vqW8O/r5EJ7F/deDgXaFbD1bUe0tNkoRPg7BqK2QcSi/pNCVF5EwPCv1X7nH0GGkCFH/fkO8YnNldPoVvxuSGivmWPTVyELx1H4gdLPJp9NsQcUc9agMz6Ilm7o4bTa7JrBdkf6LZBHWYokSsF8VHTD01yxFiUxQdOx94sxxiZBYb8bEqDcmDwHlckRJgGC+kxT39G3nEVY5glHXfCT+yNgbh+CVcXTZKnPYZBrTQPzya6GrOmlBGHXFBBRLfmS3lXqUFw2odj/Ri7GGJr4x8Y2ddDQNuShLfIgsuWGSmfjc7hdci/piyUxwWISqIwhNlXjYL0Xz5lir2orA/xhuhwYcHCMZGCrfFLKvle6mA9aoUpXimJZNhUEH76G3t0qkoDFHUd6b2H3hTdW20RWON7d1qrA5UAdXbUUsjwHRGx5NJ+ZrfuvqEL6qbKSQ1ZYjHfFEbbWMDka4yKb4KWb/d9eqPaflGHv3fZaWUA1Ri78hD9b1qaP0w8eRqKns7NuqTtultGLt6B7LRAS2V1zsgXmHJHaO+po20EI6FeoqJB7TwmLcyjXfaNfUtmhgu+jggv4sxSabH/VzkfEJYRkZvaQxOQc76/GvjkmH54WjxWkksGtW3t+HsA2PaWH0UCjaRjCeEVb7Omozkts8fXseW2XuTAiw0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
