travis:
  secure:
    BINSTAR_TOKEN: WaMHCvHyivHqe5haCol4rMdlx61YTEz8EBlWtmXCTAx9rEz0FvYoRGLgg8z/L1Gl7k/L/1PV5i+UfaFzajLpbg37Wihi1Ojb0GUiauHgn5PgTcWOM4en7pyTh+9/hhw57oPJIk4ACxHjZOAYv2f1bmohAkdm5RHZ7U0JFa/QdlvKrd1/I+UTrYlEMu86SMvtLjfwqcw0p3W2SfTrWsWfh1ulQftVsaT9SYaFCEh9kdrYx82pCBtKxCpEYOBJLEM9jEdRz206FO6buezfLKv8LhsmFAl2dqeUZOqS+oG8OZ1duuECM/mNgLOPXi+dANy+x8Xga8Kdhv1EYGz2uTvA4ShitTN7ZO3uQKy60uISOp+aCGB9sWbAzqPmjCFYQeQwmRPMWX7STRX67DnOUCyUZWgUWbpXE2Hb67oqbX9Knp6fWG4rK8NAn33cmLjBLctz5VZfsIg7E8rvfLhDLA7Zwpx2g+F30TlmDjlQCy8jenExfQOmK6/y8P3UKipvl6hSOzECgLpYH4ws8FK7HuJpQh9vdaZ3i5/KWgPad2q0rsOs2kfeycr4zgssEjpl09Be4+fjovuUOXEC6xEtYopVnaGqU9yi5Xhf3O4CJg8DLunQFRzW1WgCwjZj9DysvIHxXyzUwBWP71cvXoJnhhAb8W1aHjs3aLECoNBT7WulzGs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
